org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109
loader_version_range=[4,)

mod_id=extrahnn
mod_name=Extra Hostile Neural Networks
mod_license=MIT license
mod_version=2.2.5-port1
mod_group_id=net.lmor.extrahnn
mod_authors=LMor, nexxx_7
mod_description=Adds the ability to combine 4 models into 1, thereby obtaining more resources

# Dependencies
hostileneuralnetworks_version_id=[7.0.0,)
placebo_version_id=[10.0.2,)
jei_version=8292118
lombok=1.18.46