modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
loggFile="logo.png"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="hostilenetworks"
    type="required"
    versionRange="${hostileneuralnetworks_version_id}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="placebo"
    type="required"
    versionRange="${placebo_version_id}"
    ordering="NONE"
    side="BOTH"